### ISSUE TITLE
Error 72 : Sparse skip error(22): Invalid argument ; try --no-sparse

### ISSUE THREAD

**Issue by denfromufa** [lz4/lz4#351] opened 2017-05-04 15:09 UTC
decompressing a Virtualbox .vhd file compressed with lz4 causes error after exactly 2GB (2,147,483,648 bytes):

compression:
`D:\lz4_v1_7_5_win64\lz4.exe" -v -f "C:\VM.vhd" "D:\vm.vhd.lz4`

decompression:
`D:\lz4_v1_7_5_win64\lz4.exe" -d -v -f "D:\vm.vhd.lz4" "C:\vm.vhd`

```
*** LZ4 command line interface 64-bits v1.7.5, by Yann Collet ***
Error 72 : Sparse skip error(22): Invalid argument ; try --no-sparse
```

**Comment by denfromufa** [comment] 2017-05-04 15:22
checking integrity:

D:\>lz4_v1_7_5_win64\lz4 -t vm.vhd.lz4
vm.vhd.lz4  : decoded 104931350656 bytes

**Comment by Cyan4973** [comment] 2017-05-04 19:13
It's strange.
I would expect this issue to happen on 32-bits build, but apparently, yours is a 64-bits build.
I also guess it has been produced with mingw.

We recently had such an issue with long files with mingw.
For some reason, the `fseek()` function fails when file > 2 GB.
It's not supposed to happen, since we pay attention to only produce arguments compatible with 32-bits field. Consider it an (undocumented) limitation of mingw's standard library.

Cheap work-around is to disable `fseek()` invocation by using command `--no-sparse`.

Longer term fix : find the right set of conditions to detect this case, and either trigger another `fseek()` variant that's not susceptible to fail on large files, or disable `sparse` mode by default on this target.

Side note : it's difficult to test, since we do not use Windows laptops regularly.

**Comment by Cyan4973** [comment] 2017-05-06 23:57
Strangely enough, I'm not able to reproduce the bug with a local build.

I can download the release archive `.zip`, and observe the issue.

But when I try to compile the source code locally, using `mingw32`,
the resulting `lz4.ex`e works fine. No error after 2 GB.

So it's likely related to the build chain.

**Comment by Cyan4973** [comment] 2017-05-07 00:06
duh,
I simply forgot the issue was already fixed in `dev` branch : 
https://github.com/lz4/lz4/commit/68a358769e01606444b54e43cb62ee28abb047e5

That's why it wouldn't fail with a local build.

So the fix is already there, it's just that the pre-compiled Windows binaries v1.7.5 are not updated and do not contain the fix.

**Comment by Cyan4973** [comment] 2017-05-07 05:45
Fix : 
1. Remove buggy binaries from release - done
2. Rebuild fixed binaries locally and publish them on release ...

**Closed** 2017-05-07 06:11 UTC
Labels: bug
