### ISSUE TITLE
variable size output file

### ISSUE THREAD

**Issue by inikep** [lz4/lz4#256] opened 2016-11-06 10:02 UTC
I can confirm issue described here:
http://encode.ru/threads/2593-smallz4?p=49893&viewfull=1#post49893

It happens mainly with "-BD" and it's caused by overflow with dictBase (the part of sliding window is not available):
dictBase=FFFFFFFFF7FC7040
dictBase=FFFFFFFFF7BC7040
dictBase=FFFFFFFFF77C7040

**Comment by Cyan4973** [comment] 2016-11-06 17:01
Duplicate of #230 .

Could you describe a test / method which can put the issue into evidence ?
So far, I failed to reproduce it.

**Closed by Cyan4973** 2016-11-06 17:01 UTC
Labels: duplicate
