### ISSUE TITLE
Build error on older Linux: undefined reference to `clock_gettime'

### ISSUE THREAD

**Issue by realsimix** [lz4/lz4#450] opened 2018-01-16 07:40 UTC
If you get this error:

```
cc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -I../lib -DXXH_NAMESPACE=LZ4_  ../lib/lz4.o ../lib/lz4frame.o ../lib/lz4hc.o ../lib/xxhash.o bench.o datagen.o lz4cli.o lz4io.o -o lz4
bench.o: In function `UTIL_getTime':
/home/pkgbuild/rpmbuild/BUILD/lz4-1.8.1.2/programs/util.h:198: undefined reference to `clock_gettime'
collect2: ld returned 1 exit status
make[1]: *** [lz4] Error 1
```

Then you may need the attached patch:

[lz4-1.8.1.2-clock_gettime.patch.txt](https://github.com/lz4/lz4/files/1633979/lz4-1.8.1.2-clock_gettime.patch.txt)

**Comment by iz8mbw** [comment] 2018-01-16 07:51
Same error here

**Comment by Cyan4973** [comment] 2018-01-16 18:26
`clock_gettime()` is supposed to be more accurate than `clock()`.
However, testing its availability has proven to be a pain.

I've added more restrictive conditions to trigger the `clock_gettime()` path
in the `clockfix` branch.

Could you please test if it fixes your issue ?

**Comment by realsimix** [comment] 2018-01-17 07:07
I can confirm that the issue is fixed in the `clockfix` branch on all my platforms.

**Comment by iz8mbw** [comment] 2018-01-17 09:31
I confirm that the issue is fixed in the `clockfix` branch too, tested on Raspberry Pi 1 and Raspberry Pi 2.
Thanks!

**Closed** 2018-01-17 20:45 UTC
Labels: build issue

**Comment by jakirkham** [comment] 2018-04-18 02:26
FTR the issue is that `-lrt` should be included in the `LDFLAGS`, but does not appear to be (or at least does not appear to be in any released versions).
