### ISSUE TITLE
unable to pipe --list output

### ISSUE THREAD

**Issue by rmungu** [lz4/lz4#840] opened 2020-02-06 15:53 UTC
Hi,

I'm attempting to pipe the output of the lz4 --list option, but it only seems to send to stdout with a warning.
ex.

`>lz4 --list example.dmp.lz4 | find "example.dmp"
`

`Warning : using stdout as default output. Do not rely on this behavior: use explicit `-c` instead !
    Frames           Type Block  Compressed  Uncompressed     Ratio   Filename
         1       LZ4Frame   B7I       1.11G         6.57G     16.86%  example.dmp.lz4
`

where I was expecting the following single line:

`         1       LZ4Frame   B7I       1.11G         6.57G     16.86%  example.dmp.lz4
`

Using the -c option simply removes the warning:

`>lz4 -c --list example.dmp.lz4 | find "example.dmp"
`

`    Frames           Type Block  Compressed  Uncompressed     Ratio   Filename
         1       LZ4Frame   B7I       1.11G         6.57G     16.86%  example.dmp.lz4
`

I've tried both the 32 & 64 bit v1.9.2 version on Windows.  The idea is to direct the output of the find to a text file:

`lz4 --list example.dmp.lz4 | find "example.dmp" > example.txt
`

This should produce the example.txt file with a single line, however all output from the --list option goes to cmd window and example.txt is empty.

I'm attempting to get the similar output as:

unzip -l example.dmp.zip | find "example.dmp" > example.txt
gzip -list example.dmp.gz | find "example.dmp" > example.txt

**Comment by Cyan4973** [comment] 2020-02-06 17:10
It's reasonable to expect the "Warning" message to not be present when requesting `--list`.

It seems you would also prefer the header/title line to not be present.
Using `gzip` as a reference for the intended behavior is a good point.

**Comment by rmungu** [comment] 2020-02-06 18:15
The "Warning" and header/title lines output is all acceptable - no issues there.  I was including that to show what I had tried and results.

The output with the --list option does not seem to want to pipe to other command (find or grep) in order to send the 1 line to the .txt file.

I've also tried send the output to a file

`> lz4 --list example.lz4 > example.txt` 

and I get an empty text file.

**Comment by filipecalasans** [comment] 2020-02-07 05:52
See PR #842 as a fix for this issue.

**Comment by Cyan4973** [comment] 2020-02-07 18:18
Fixed by @filipecalasans in #842

**Closed as completed by Cyan4973** 2020-02-07 18:18 UTC
Labels: feature request, good first issue
