### ISSUE TITLE
Question regarding the  ptr arithmetic in lz4.c

### ISSUE THREAD

**Issue by JoachimSchneider** [lz4/lz4#485] opened 2018-03-21 13:22 UTC
Dear Developers,
while compiling the lz4 library on OS/400 (the OS running on the IBM midrange AS/400 computers) we found a questionable pointer arithmetic construct in lib/lz4.c:

We guess that line 1046 of lz4/lib/lz4.c should read
  (LZ4_dict->dictionary + LZ4_dict->currentOffset > src)) {   /* address space overflow */
instead of
       ((uptrval)LZ4_dict->currentOffset > (uptrval)src)) {   /* address space overflow */

Attached is a patch file (lz4.c.diff.zip)
[lz4.c.diff.zip](https://github.com/lz4/lz4/files/1833361/lz4.c.diff.zip)

After applying the modification w successfully ran all the tests contained in the lz4/tests directory (make test).

Best Regards,
Joachim Kern and Joachim Schneider, SAP SE

**Comment by Cyan4973** [comment] 2018-03-21 14:29
Thanks for your report @JoachimSchneider !

I understand a compiler might feel this comparison is questionable, since this test is comparing an `U32` index to a pointer, which are 2 things of different nature.
This is valid though, since both are casted to `uptrval` prior to the comparison.

And the test is correct too.
The issue it solves is the following : `currentOffset` will be used to [calculate `dictBase`](https://github.com/lz4/lz4/blob/dev/lib/lz4.c#L620), which is defined as `src - currentOffset`. Therefore, if `src` < `currentOffset`, the resulting `dictBase` will underflow, and become a high address value. This _may_ cause troubles later on as there are branch decisions based on ptr comparisons, with the assumption that a `match` is necessarily < `currentPtr`. 
Note that problems are not "guaranteed", it also depends on bad luck, distribution of values in the hash table, etc.

Anyway, the main idea here is to make sure `src - currentOffset = dictBase` remains a positive number, so that we can then guarantee that `dictBase < src`.
This test achieve this goal.

However, your compiler complains, maybe because the underlying types, prior casting to `uptrval`, are of different nature.

Maybe something like that could work then : 
`(uptrval)((BYTE*)NULL + LZ4_dict->currentOffset) > (uptrval)src`

It's the same test, but now `(BYTE*)NULL + LZ4_dict->currentOffset` is officially a pointer before its conversion to `uptrval`, so it might calm down compiler warning.

Another potential variant is : 
`(BYTE*)(uptrval)LZ4_dict->currentOffset > src`
now both sides are `BYTE*` pointers.

I can't test these variants on my side though, since none of my accessible compilers ever complained about previous formulation.

**Comment by JoachimSchneider** [comment] 2018-03-22 18:36
Hello Yann,

thank you for the explanation.

> Anyway, the main idea here is to make sure `src - currentOffset = dictBase` remains a positive number, > so that we can then guarantee that `dictBase < src`.
Would it also be possible to test directly what one wants to test i.e.

src - dictBase < src

This way one would only use operations which are allowed by ANSI-C-89, namely addition of integers to pointers and using the relational operators on pointers (Sections 3.3.6 and 3.3.8 of ANSI X3.159-1989 "Programming Language C" and sections 6.5.6 and 6.5.8 of ISO/IEC 9899:TC3)

The reason why i am dwelling on this point is that on OS/400 we have 16-Byte pointers but our largest integer type (long long int) has 8 Bytes, so there is no way to use uintptr_t-conversions (the uintptr_t type is not available on OS/400, the ISO/IEC 9899 classifies this type as "optional" (section 7.18.1.4)); even if we had an 16-Byte integer type it would not be possible as pointers are handled very special on OS/400 because of the so called 'single-level store' used there.

So would

src - dictBase < src

be a possibility?

Thank you in advance,
Joachim Schneider


On Wed, 21 Mar 2018, Yann Collet wrote:

> Thanks for your report @JoachimSchneider !
>
> I understand a compiler might feel this comparison is questionable, since this test is comparing an `U32` index to a pointer, which are 2 things of different nature.
> This is valid though, since both are casted to `uptrval` prior to the comparison.
>
> And the test is correct too.
> The issue it solves is the following : `currentOffset` will be used to [calculate `dictBase`](https://github.com/lz4/lz4/blob/dev/lib/lz4.c#L620), which is defined as `src - currentOffset`. Therefore, if `src` < `currentOffset`, the resulting `dictBase` will underflow, and become a high address value. This _may_ cause troubles later on as there are branch decisions based on ptr comparisons, with the assumption that a `match` is necessarily < `currentPtr`.
> Note that problems are not "guaranteed", it also depends on bad luck, distribution of values in the hash table, etc.
>
> Anyway, the main idea here is to make sure `src - currentOffset = dictBase` remains a positive number, so that we can then guarantee that `dictBase < src`.
> This test achieve this goal.
>
> However, your compiler complains, maybe because the underlying types, prior casting to `uptrval`, are of different nature.
>
> Maybe something like that could work then :
> `(uptrval)((BYTE*)NULL + LZ4_dict->currentOffset) > (uptrval)src`
>
> It's the same test, but now `(BYTE*)NULL + LZ4_dict->currentOffset` is officially a pointer before its conversion to `uptrval`, so it might calm down compiler warning.
>
> Another potential variant is :
> `(BYTE*)(uptrval)LZ4_dict->currentOffset > src`
> now both sides are `BYTE*` pointers.
>
> I can't test these variants on my side though, since none of my accessible compilers ever complained about previous formulation.
>
>

--
%%
% Dr. Joachim Schneider
%
% SAP on IBM i, DB/OS Platforms
% SAP SE, Dietmar-Hopp-Allee 16, 69190 Walldorf, Germany
%
% Tel.: +49/6227/7-68715
% mailto: joachim.schneider@sap.com
%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Pflichtangaben/Mandatory Disclosure Statements:

http://www.sap.com/germany/about/company/legal/impressum_DE.epx

Diese E-Mail kann Betriebs- oder Geschäftsgeheimnisse oder sonstige
vertrauliche Informationen enthalten. Sollten Sie diese E-Mail
irrtuemlich erhalten haben, ist Ihnen eine Kenntnisnahme des Inhalts,
eine Vervielfaeltigung oder Weitergabe der E-Mail ausdruecklich
untersagt. Bitte benachrichtigen Sie uns und vernichten Sie die
empfangene E-Mail. Vielen Dank.

This e-mail may contain trade secrets or privileged, undisclosed, or
otherwise confidential information. If you have received this e-mail in
error, you are hereby notified that any review, copying, or distribution
of it is strictly prohibited. Please inform us immediately and destroy
the original transmittal. Thank you for your cooperation.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

**Comment by JoachimSchneider** [comment] 2018-03-23 09:42
Hello Yann,

sorry, my last mail contained a typo (currentOffset <--> dictBase). Here is the correct version:

thank you for the explanation.

> Anyway, the main idea here is to make sure `src - currentOffset = dictBase`
> remains a positive number, > so that we can then guarantee that `dictBase <
> src`.

Would it also be possible to test directly what one wants to test i.e.

src - currenOffset < src

This way one would only use operations which are allowed by ANSI-C-89, namely
addition of integers to pointers and using the relational operators on
pointers (Sections 3.3.6 and 3.3.8 of ANSI X3.159-1989 "Programming Language
C" and sections 6.5.6 and 6.5.8 of ISO/IEC 9899:TC3)

The reason why i am dwelling on this point is that on OS/400 we have 16-Byte
pointers but our largest integer type (long long int) has 8 Bytes, so there
is no way to use uintptr_t-conversions (the uintptr_t type is not available
on OS/400, the ISO/IEC 9899 classifies this type as "optional" (section
7.18.1.4)); even if we had an 16-Byte integer type it would not be possible
as pointers are handled very special on OS/400 because of the so called
'single-level store' used there.

So would asserting

src - currenOffset < src

be a possibility?

Thank you in advance,
Joachim Schneider

On Wed, 21 Mar 2018, Yann Collet wrote:
>
> Thanks for your report @JoachimSchneider !
>
> I understand a compiler might feel this comparison is questionable, since
> this test is comparing an `U32` index to a pointer, which are 2 things of
> different nature.
> This is valid though, since both are casted to `uptrval` prior to the
> comparison.
>
> And the test is correct too.
> The issue it solves is the following : `currentOffset` will be used to
> [calculate `dictBase`](https://github.com/lz4/lz4/blob/dev/lib/lz4.c#L620),
> which is defined as `src - currentOffset`. Therefore, if `src` <
> `currentOffset`, the resulting `dictBase` will underflow, and become a high
> address value. This _may_ cause troubles later on as there are branch
> decisions based on ptr comparisons, with the assumption that a `match` is
> necessarily < `currentPtr`.
> Note that problems are not "guaranteed", it also depends on bad luck,
> distribution of values in the hash table, etc.
>
> Anyway, the main idea here is to make sure `src - currentOffset = dictBase`
> remains a positive number, so that we can then guarantee that `dictBase <
> src`.
> This test achieve this goal.
>
> However, your compiler complains, maybe because the underlying types, prior
> casting to `uptrval`, are of different nature.
>
> Maybe something like that could work then :
> `(uptrval)((BYTE*)NULL + LZ4_dict->currentOffset) > (uptrval)src`
>
> It's the same test, but now `(BYTE*)NULL + LZ4_dict->currentOffset` is
> officially a pointer before its conversion to `uptrval`, so it might calm
> down compiler warning.
>
> Another potential variant is :
> `(BYTE*)(uptrval)LZ4_dict->currentOffset > src`
> now both sides are `BYTE*` pointers.
>
> I can't test these variants on my side though, since none of my accessible
> compilers ever complained about previous formulation.
>
>

--
%%
% Dr. Joachim Schneider
%
% SAP on IBM i, DB/OS Platforms
% SAP SE, Dietmar-Hopp-Allee 16, 69190 Walldorf, Germany
%
% Tel.: +49/6227/7-68715
% mailto: joachim.schneider@sap.com
%%
>
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Pflichtangaben/Mandatory Disclosure Statements:
>
http://www.sap.com/germany/about/company/legal/impressum_DE.epx
>
Diese E-Mail kann Betriebs- oder Geschäftsgeheimnisse oder sonstige
vertrauliche Informationen enthalten. Sollten Sie diese E-Mail
irrtuemlich erhalten haben, ist Ihnen eine Kenntnisnahme des Inhalts,
eine Vervielfaeltigung oder Weitergabe der E-Mail ausdruecklich
untersagt. Bitte benachrichtigen Sie uns und vernichten Sie die
empfangene E-Mail. Vielen Dank.
>
This e-mail may contain trade secrets or privileged, undisclosed, or
otherwise confidential information. If you have received this e-mail in
error, you are hereby notified that any review, copying, or distribution
of it is strictly prohibited. Please inform us immediately and destroy
the original transmittal. Thank you for your cooperation.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

**Comment by JoachimSchneider** [comment] 2018-03-23 12:04
Sorry,

my last statemnent contained a typo (currentOffset <--> dictBase).

My proposal is to assert that the condition

src - currenOffset < src

is true. This would detect underflow, as this little program shows:

=================================================================================
#include <stdio.h>

#define PPOS  (10000)

void pptr(void *p)
{
    int  l   = sizeof(p);
    char *cp = (char *)&p;
    int  i   = 0;

    printf("%s", "0x");
    for ( i = 0; i < l; i++ )  {
        printf("%02X", (unsigned int)*cp++);
    }
}

int main(int argc, char *argv[])
{
    int  ofs = 1;
    char *cp = (char *)PPOS;

    for (;;) {
        if ( !(cp - ofs < cp) )  {   /* Check for UNDERFLOW: */
            printf("ofs = 0x%X, cp = ", ofs);
            pptr(cp);
            printf("%s", "\n");

            break;
        }
        ofs++;
    }

    return 0;
}


/**
  * EOF
  **/
=================================================================================
Running it on Linux:
ofs = 0x2711, cp = 0x1027000000000000

Running it on OS/400:
ofs = 0x2711, cp = 0x80000000000000000000000000002710
=================================================================================


Greetings,
Joachim


On Thu, 22 Mar 2018, Nick Terrell wrote:

> We can't compute `dictBase` before the check, since `dictBase = src - currentOffset`, and if `currentOffset > src`, this results in a pointer underflow, which is undefined behavior.
>
> AFAIK the only way to do this check without undefined behavior is by casting the pointer to some integer-type value, like `uintptr_t`, but that won't work on your platform. Would `NULL + currentOffset > src` work on your platform? This has undefined behavior, since `NULL + currentOffset` doesn't point to a valid object, and the two pointers aren't pointing into the same object, so they can't be compared.
>
>

--
%%
% Dr. Joachim Schneider
%
% SAP on IBM i, DB/OS Platforms
% SAP SE, Dietmar-Hopp-Allee 16, 69190 Walldorf, Germany
%
% Tel.: +49/6227/7-68715
% mailto: joachim.schneider@sap.com
%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Pflichtangaben/Mandatory Disclosure Statements:

http://www.sap.com/germany/about/company/legal/impressum_DE.epx

Diese E-Mail kann Betriebs- oder Geschäftsgeheimnisse oder sonstige
vertrauliche Informationen enthalten. Sollten Sie diese E-Mail
irrtuemlich erhalten haben, ist Ihnen eine Kenntnisnahme des Inhalts,
eine Vervielfaeltigung oder Weitergabe der E-Mail ausdruecklich
untersagt. Bitte benachrichtigen Sie uns und vernichten Sie die
empfangene E-Mail. Vielen Dank.

This e-mail may contain trade secrets or privileged, undisclosed, or
otherwise confidential information. If you have received this e-mail in
error, you are hereby notified that any review, copying, or distribution
of it is strictly prohibited. Please inform us immediately and destroy
the original transmittal. Thank you for your cooperation.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

**Comment by Cyan4973** [comment] 2018-03-23 17:47
I'm afraid that `src - currentOffset < src` is already [undefined behavior](https://news.ycombinator.com/item?id=4374598). 

I understand that this operation is expected to work
whenever the address space is not segmented, which is generally the case,
and whenever this operation is actually performed.

Problem is, due to UB nature of this operation,
some compiler will feel free to perform optimizations based on the following assumption :
since `currentOffset` is `unsigned`, it is `>= 0`.
Therefore `src - currentOffset` is necessarily `<= currentOffset`,
assuming it doesn't overflow, __which I will assume because pointer overflow is UB__.
Therefore, `src - currentOffset < src` is always true, except when `currentOffset == 0`.
Therefore, let's replace this test by the faster alternative `currentOffset != 0`.

Btw, the correct equivalent test is `src - currentOffset <= src`,
in which case, using the same scenario as above,
it can be replaced by `1`, hence eliminate a branch,
which is even better, so some compilers will not miss such a chance.

Sure, it's a complex optimization scenario, and many compilers will not do that.
The problem is, no one can guarantee that no compiler will _ever_ do that.
So it becomes a latent bug, that may trigger in the future, or with the proper set of optimization flags.

In contrast `(uptrval)currentOffset > (uptrval)src` is perfectly defined.
There is no 2 ways to interpret this comparison.

**Comment by terrelln** [comment] 2018-03-23 17:48
In fact current compilers are very liable to optimize it out https://godbolt.org/g/DTyDg9 and https://godbolt.org/g/CtVPYc.

**Comment by Cyan4973** [comment] 2018-04-26 23:12
@JoachimSchneider, would you have time to test latest `dev` branch update on your target system ?
We plan a new LZ4 release soon, and it would be better if we could potentially integrate fixes for your target system.

**Comment by Cyan4973** [comment] 2018-09-05 23:19
We have updated our tooling and library source code
to deal with pointer arithmetic and overflow risks,
especially when source pointer is at a very low address range, where risks are maximized.

We hope that it will work nicely with your target platform `OS/400`.

If it doesn't, we're happy to help and investigate.

Save any news on this topic, I'll close this thread in the near future.

**Comment by JoachimSchneider** [comment] 2018-09-07 10:20
Hello Yann,

thank you for the information. I will test the new LZ4 on OS/400. During the next week i'll tell you the results.

Regards,
Joachim


On Wed, 5 Sep 2018, Yann Collet wrote:

> We have updated our tooling and library source code
> to deal with pointer arithmetic and overflow risks,
> especially when source pointer is at a very low address range, where risks are maximized.
>
> We hope that it will work nicely with your target platform `OS/400`.
>
> If it doesn't, we're happy to help and investigate.
>
> Save any news on this topic, I'll close this thread in the near future.
>
>

--
%%
% Dr. Joachim Schneider
%
% SAP on IBM i, DB/OS Platforms
% SAP SE, Dietmar-Hopp-Allee 16, 69190 Walldorf, Germany
%
% Tel.: +49/6227/7-68715
% mailto: joachim.schneider@sap.com
%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Pflichtangaben/Mandatory Disclosure Statements:

http://www.sap.com/germany/about/company/legal/impressum_DE.epx

Diese E-Mail kann Betriebs- oder Geschäftsgeheimnisse oder sonstige
vertrauliche Informationen enthalten. Sollten Sie diese E-Mail
irrtuemlich erhalten haben, ist Ihnen eine Kenntnisnahme des Inhalts,
eine Vervielfaeltigung oder Weitergabe der E-Mail ausdruecklich
untersagt. Bitte benachrichtigen Sie uns und vernichten Sie die
empfangene E-Mail. Vielen Dank.

This e-mail may contain trade secrets or privileged, undisclosed, or
otherwise confidential information. If you have received this e-mail in
error, you are hereby notified that any review, copying, or distribution
of it is strictly prohibited. Please inform us immediately and destroy
the original transmittal. Thank you for your cooperation.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

**Comment by JoachimSchneider** [comment] 2018-09-12 05:45
Hello Yann,

i have tested your updated tooling and library source code on
OS/400. The tests were based on a clone of the git repository from Sep
07 2018 (git clone -b dev https://github.com/lz4/lz4.git).

I had to do some slight modifications to make it work on OS/400. These
modifcations were necessary because

(a) The OS/400 platform uses 16-bit pointers. At one  place a logic like
     'if not 8-byte-ptr then 4-byte-ptr' was used (lib/lz4.c).

(b) The OS/400 C-compiler seems to be a litle bit more pedantic with
     enumerations (lib/lz4hc.h, lib/lz4hc.c).

(c) There are some structures whose size needs to be enlarged when
     16-byte-pointers are used (lib/lz4hc.h, lib/lz4.h)

Appended to this mail is a ZIP-archive containing

(0) The output of 'git log' to unambiguously identify the version used
     for my tests:

     git-log-lz4_20180907.txt

(1) The diffs to the files mentioned above:

     DIFFS/lib/lz4.h.diff
     DIFFS/lib/lz4.c.diff
     DIFFS/lib/lz4frame.h.diff
     DIFFS/lib/lz4hc.h.diff
     DIFFS/lib/lz4hc.c.diff

(2) The original version of these files:

     ORG/lib/lz4.h
     ORG/lib/lz4.c
     ORG/lib/lz4frame.h
     ORG/lib/lz4hc.h
     ORG/lib/lz4hc.c

(3) A make-script (CL language) for OS/400. The comments at the
     beginning of the file give the necessary usage instructions.

     programs/MakeCmdOS400.CL

(4) A screen shot showing the LZ4-Program running on OS/400 --- note
     especially the 128-Bit OS.

     OS400_START.JPEG

(5) This file

     Readme.txt


Best Regards,
Dr. Joachim Schneider,  SAP SE



On Wed, 5 Sep 2018, Yann Collet wrote:

> We have updated our tooling and library source code
> to deal with pointer arithmetic and overflow risks,
> especially when source pointer is at a very low address range, where risks are maximized.
>
> We hope that it will work nicely with your target platform `OS/400`.
>
> If it doesn't, we're happy to help and investigate.
>
> Save any news on this topic, I'll close this thread in the near future.
>
>


--
%%
% Dr. Joachim Schneider
%
% SAP on IBM i, DB/OS Platforms
% SAP SE, Dietmar-Hopp-Allee 16, 69190 Walldorf, Germany
%
% Tel.: +49/6227/7-68715
% mailto: joachim.schneider@sap.com
%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Pflichtangaben/Mandatory Disclosure Statements:

http://www.sap.com/germany/about/company/legal/impressum_DE.epx

Diese E-Mail kann Betriebs- oder Geschäftsgeheimnisse oder sonstige
vertrauliche Informationen enthalten. Sollten Sie diese E-Mail
irrtuemlich erhalten haben, ist Ihnen eine Kenntnisnahme des Inhalts,
eine Vervielfaeltigung oder Weitergabe der E-Mail ausdruecklich
untersagt. Bitte benachrichtigen Sie uns und vernichten Sie die
empfangene E-Mail. Vielen Dank.

This e-mail may contain trade secrets or privileged, undisclosed, or
otherwise confidential information. If you have received this e-mail in
error, you are hereby notified that any review, copying, or distribution
of it is strictly prohibited. Please inform us immediately and destroy
the original transmittal. Thank you for your cooperation.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

**Comment by JoachimSchneider** [comment] 2018-09-13 06:58
Hello Yann,
i have attached the missing ZIP-archive:
[OS400_LZ4.ZIP](https://github.com/lz4/lz4/files/2378031/OS400_LZ4.ZIP)
Greetings,
Joachim

**Comment by Cyan4973** [comment] 2018-09-13 19:42
Thanks @JoachimSchneider , 
I downloaded your package, it's full of interesting learnings.
I'll study it a bit more, and see what can be used for upstream version.

**Comment by JoachimSchneider** [comment] 2018-09-15 12:09
Thank you for including part of my suggestions.

What can be done to include also the OS/400 specific changes (those inside the
ifdef __OS400
...
endif 
parts)? They are all related to the fact that OS/400 has 16-byte pointers.

Thank you, greetings,
Joachim

**Comment by Cyan4973** [comment] 2018-09-17 23:20
Hi @JoachimSchneider ,

For this second part, the main issue is how the API is being currently used.

`LZ4_STREAMSIZE_U64` macro constant was initially exposed to allow users to statically allocate some memory and pass that memory area to functions such as `LZ4_compress_fast_extState()` which make it possible to explicitly manage the context (which is the main consumer of memory).
The goal was to make this area opaque to the user, while making it possible to allocate it statically (on stack, or as part of another structure). `LZ4_STREAMSIZE_U64` made this capability accessible, and was meant to define this area as a table of 8-bytes elements, thus ensuring correct alignment (without resorting to compiler-specific or C11 extensions). 

This technique was adopted at a time when the context was provided as a `void*` pointer to functions.

Later, the API was partially updated to use incomplete types instead. This methodology is preferable because the C compiler can now detect when a wrong pointer type is passed to the function, thus preventing a whole class of errors.

Unfortunately, now, the combination of the 2 techniques breaks the [strict aliasing rule](https://www.approxion.com/?p=2656). The opaque area and the incomplete type are now 2 different type. They shall not alias.

I couldn't find any way to reconcile the two constraints. So, in order to preserve the benefit of type checking, I decided to publish the content of the context structure, foregoing the benefits of internal opacity, and trying to compensate this situation with scary member names (`internal_donotuse`).
This is in essence the situation of today, with the type definition covered here : 
https://github.com/lz4/lz4/blob/dev/lib/lz4.h#L546

Anyone looking for static allocation should simply allocate an `LZ4_stream_t` now, directly on stack, or in a struct. It will get translated into a `union LZ4_stream_u`, which contains both the definition of the internal state itself (`struct LZ4_stream_t_internal`) and the table of 64-bit elements as before. `LZ4_STREAMSIZE_U64` is still there, for compatibility with existing programs. The size of this union being the larger of both its members, it is necessarily large enough, and its alignment is necessarily correct, even if pointers are 128-bit, like AS-400.

One problem is, compilation does not proceed, because there is a `static_assert` which verifies that the context size `LZ4_STREAMSIZE_U64` defined as a table of 8-bytes elements is large enough to contain the internal state structure. That's where it breaks with pointers of 128-bit.

The `static_assert` dates from a time where, externally, the only way to statically allocate space for the context was the constant `LZ4_STREAMSIZE_U64`. (Note : a safer approach is to use [`LZ4_sizeofState()`](https://github.com/lz4/lz4/blob/dev/lib/lz4.h#L188) instead, which is necessarily correct, but is not suitable for static allocation). Since the context structure is now published, is it still necessary ?

I would say no, at least no for new programs.
But what about older ones, which may still depend on this constant ?

That's where it becomes more dangerous.
And it's difficult to know.
The more cautious approach is to keep the constant available, in case some users still need it.

OK, so what about just bumping its value, so that it covers case where pointers are 128-bit ?
Possible, but I was then worried about possible version mismatch.

The static allocation mechanism is clearly labelled "for static linking only". 
Unfortunately, there is always a risk that an application nonetheless uses it in combination with a dynamic library. 
So what then ? If an application provides a buffer "small" to a library which expects a buffer "large", then the library will start initializing it, and produce a segfault. That's the risk.

So I've been pondering this risk these last few days, and concluded that,
actually, there is no such problem.
Internally, the library doesn't really use `LZ4_STREAMSIZE_U64`, but uses directly the definition of internal state structure instead.
So even if `LZ4_STREAMSIZE_U64` is increased, it will make users of the new library version allocate more space, but this additional space is actually not needed and will not be initialized.
As a consequence, programs using an old value of `LZ4_STREAMSIZE_U64` but linking to the new version of the library will provide less space, but it will not trigger any problem, because this additional space is not needed : the space effectively used is still the same.

So the only difference will be for systems with 128-bit pointers, which currently cannot compile. So they can't be impacted by the "old value".

Going a bit farther, since the context structure is now published, I could make `LZ4_STREAMSIZE_U64` actually depend on it. So the size, instead of being constant on all targets, would depend on underlying ABI, saving a few bytes for 32-bit system, and expanding as needed for 128-bit ones.

My last problem is that automatic ABI / API compatibility tools will detect the change and declare it an interface break, even if the size difference is just cosmetic and does not break anything at runtime (no segfault). So maybe the change should only impact 128-bit systems.

As one can see, there are solutions.
The major point is to correctly manage legacy software, in order to introduce such changes without breaking existing applications.

**Comment by JoachimSchneider** [comment] 2018-09-24 06:12
Hello Yann,
i already commented on your pull request (https://github.com/lz4/lz4/pull/578) --- sorry for repeating it here; with one additional change it compiles and works on AS/400:

*********************************************************************************
--- lz4.h       2018/09/20 08:57:50     1.1
+++ lz4.h       2018/09/20 09:07:54
@@ -564,7 +564,7 @@
  *         this definition is not API/ABI safe,
  *         and may change in a future version !
  */
-#define LZ4_STREAMDECODESIZE_U64 (4 + ((sizeof(void*)==16) ? 2 : 0) /*AS-400*/ )
+#define LZ4_STREAMDECODESIZE_U64 (4 + ((sizeof(void*)==16) ? 4 : 0) /*AS-400*/ )
 #define LZ4_STREAMDECODESIZE     (LZ4_STREAMDECODESIZE_U64 * sizeof(unsigned long long))
 union LZ4_streamDecode_u {
     unsigned long long table[LZ4_STREAMDECODESIZE_U64];
*********************************************************************************
Greetings,
Joachim

**Comment by Cyan4973** [comment] 2018-09-26 20:57
Patch merged into `dev`

**Closed by Cyan4973** 2018-09-26 20:57 UTC

**Comment by Cyan4973** [comment] 2018-09-27 16:19
Thanks for the feedback @JoachimSchneider !
