### ISSUE TITLE
alignment checks added to lz4hc.c don't work even on linux

### ISSUE THREAD

**Issue by gkodinov** [lz4/lz4#827] opened 2020-01-22 15:32 UTC
This check in lz4hc.c (e.g. in LZ4_initStreamHC())
#ifndef _MSC_VER  /* for some reason, Visual fails the aligment test on 32-bit x86 :
                   * it reports an aligment of 8-bytes,
                   * while actually aligning LZ4_streamHC_t on 4 bytes. */
    assert(((size_t)state & (LZ4_streamHC_t_alignment() - 1)) == 0);  /* check alignment */
#endif

doesn't work even on non-MS Windows 32 bit builds.

The problem is that, while the alignment is checked, no measures are taken to ensure that the buffers passed are aligned. On 64 bit builds it's OK since (apparently) malloc() returns memory alligned on 8 bytes. But on 32 bit it returns memory alligned on 4 bytes and that is not enough for the structure checked here. 
E.g. for wrong allocation look at:
 937 LZ4_streamHC_t* LZ4_createStreamHC(void)
 938 {
 939     LZ4_streamHC_t* const LZ4_streamHCPtr = (LZ4_streamHC_t*)ALLOC(sizeof(LZ4_streamHC_t));
 940     if (LZ4_streamHCPtr==NULL) return NULL;
 941     LZ4_initStreamHC(LZ4_streamHCPtr, sizeof(*LZ4_streamHCPtr));  /* full initialization, malloc'ed buffer      can be full of garbage */
 942     return LZ4_streamHCPtr;
 943 }

**Comment by Cyan4973** [comment] 2020-01-24 22:09
Do you have an example of failure ?

memory aligned on 4 bytes is correct for 32-bit systems,
the check should just determine and verify this condition,
and not "upgrade" the requirement to 8-bytes, which would be incorrect.

**Comment by gkodinov** [comment] 2020-01-25 08:33
The only reproduction I have is replacing the lz4 sources into the mysql
server source tree, compiling it on a 32 bit linux and running the tests.

Best Regards,
Georgi Kodinov

На сб, 25.01.2020 г. в 0:09 Yann Collet <notifications@github.com> написа:

**Comment by kotnis** [comment] 2020-04-04 15:44
Seems this is solution: https://github.com/lz4/lz4/issues/851

**Comment by jgh-** [comment] 2020-04-27 10:19
Piggybacking on this issue, it looks as if `LZ4_initStreamHC` can (and apparently does) fail, but this failure is never checked for in `LZ4_createStreamHC` allowing the program to proceed with garbage data. The result from initStream is only intermittently checked in other functions: `LZ4_compress_HC_extStateHC` and `LZ4_compress_HC_destSize` check for failure but `LZ4_resetStreamHC`, `LZ4_resetStreamHC_fast`, and `LZ4_loadDictHC` do not (although in the case of reset it may not matter since presumably alignment has already been verified the first time).

**Comment by remittor** [comment] 2020-09-29 07:31
> memory aligned on 4 bytes is correct for 32-bit systems,

This is a controversial statement! Take a look at this:
https://github.com/facebook/zstd/blob/236b98e7de8f82ad901ef64034bccdd35000b9d4/lib/compress/zstd_compress.c#L97
https://github.com/facebook/zstd/blob/236b98e7de8f82ad901ef64034bccdd35000b9d4/lib/compress/zstd_compress.c#L3624
https://github.com/facebook/zstd/blob/236b98e7de8f82ad901ef64034bccdd35000b9d4/lib/decompress/zstd_ddict.c#L198
https://github.com/facebook/zstd/blob/236b98e7de8f82ad901ef64034bccdd35000b9d4/lib/decompress/zstd_decompress.c#L128

And in general, it is better to make memory allocation in the same way as in `Zstd`:
https://github.com/facebook/zstd/blob/236b98e7de8f82ad901ef64034bccdd35000b9d4/lib/compress/zstd_cwksp.h#L164-L168
https://github.com/facebook/zstd/blob/236b98e7de8f82ad901ef64034bccdd35000b9d4/lib/compress/zstd_cwksp.h#L309-L312
https://github.com/facebook/zstd/blob/236b98e7de8f82ad901ef64034bccdd35000b9d4/lib/compress/zstd_compress.c#L3624-L3629

**Comment by Cyan4973** [comment] 2020-10-02 17:58
> it looks as if LZ4_initStreamHC can (and apparently does) fail, but this failure is never checked for in LZ4_createStreamHC

This issue, reported by @jgh-, is now fixed in `dev` branch.

**Comment by Cyan4973** [comment] 2020-10-02 20:31
I've been testing this issue again.

So far, on 32-bit Linux, the alignment detector seems to work as intended.
I created a new test which attempts initialization of several contexts aligned differently. They all pass fine : 
```
LZ4_initStreamHC with multiple valid alignments : hc1(0xbf8f3188) hc2(0xbf9331c4) hc3(0xbf973200) size(0x40038): OK
```
The most interesting one is `hc2`, which is 4-byte aligned but not 8-byte aligned. Yet it still initializes properly.
(note: there is another test that checks that blatantly incorrectly aligned states fail initialization, so they don't always succeed).

It also validates expectation : on 32-bit (x86) systems, alignment on 4-bytes is enough,
it is detected correctly, at least as far as these versions of Linux are concerned (`Ubuntu Precise 32-bit 12.04`, `gcc-4.4.7`, `gcc v4.6.3`, `clang v3.0`, `clang v3.4`)  (`Ubuntu Trusty 14.04`, `gcc-4.8.4`)  (`Lubuntu 32-bit 16.04`, `gcc v4.7.4`, `gcc v5.4.0`, `clang v3.5.2`, `clang v3.8.0` ,`clang v8.0.0`).

__I have yet to find a 32-bit scenario in which this alignment check fails.__
Not saying it doesn't exist, just saying that I would be glad to get some clues about how to reproduce it.

**Comment by Cyan4973** [comment] 2020-10-03 01:40
OK, so now for an even more interesting follow-up : 
I've restored alignment check for Visual Studio 32-bit,
and tested it on AppveyorCI,
https://ci.appveyor.com/project/YannCollet/lz4-1lndh/build/job/w2dhnx4qgufshr7l#L375
and everything seems to work fine ....

LZ4HC state allocated on 4-byte aligned memory pass the alignment test and get initialized properly.

I still don't get it : where is the problem that resulted in removing that check for MSVC ?

**Comment by remittor** [comment] 2020-10-03 04:37
> So far, on 32-bit Linux, the alignment detector seems to work as intended.

https://github.com/lz4/lz4/blob/d1414fd5524a70d47656e0fceb58ee10dc573b75/lib/lz4.c#L1409-L1417
This function can return a value other than 4 for 32-bit.
This function does not respect the global compiler settings. For example this: `-fpack-struct=2`

**Comment by remittor** [comment] 2020-10-03 05:21
> I've restored alignment check for Visual Studio 32-bit,

Here are the test results at MSVC 2008 (32-bit):
```
sizeof(void*) = 4
LZ4_STREAMSIZE_U64 = 2052
LZ4_STREAMSIZE_U64 * 8 = 16416
sizeof(LZ4_stream_t_internal) = 16404
LZ4_stream_t_alignment() = 8
```
And this function can return `NULL`:
https://github.com/lz4/lz4/blob/d1414fd5524a70d47656e0fceb58ee10dc573b75/lib/lz4.c#L1427

The reason why function `LZ4_stream_t_alignment` returned 8 is in this:
https://github.com/lz4/lz4/blob/d1414fd5524a70d47656e0fceb58ee10dc573b75/lib/lz4.h#L635

If there is a type `uint64_t` in the structure, the entire structure will be always aligned by 8 bytes.

Look at this: https://stackoverflow.com/a/5435954

And look at this: https://github.com/svn2github/lz4/commit/006a2e05c930894fef50f95816e596d86bd7d23a#diff-5bdf7e3437c9e47d597bda9e898d4c53L175-R184

**Comment by remittor** [comment] 2020-10-06 12:29
@Cyan4973
> memory aligned on 4 bytes is correct for 32-bit systems,
> the check should just determine and verify this condition,
> and not "upgrade" the requirement to 8-bytes, which would be incorrect.

Look at this: https://github.com/lz4/lz4/blob/d1414fd5524a70d47656e0fceb58ee10dc573b75/lib/lz4.h#L198
Source: https://github.com/lz4/lz4/commit/1b17bf2ab8cf66dd2b740eca376e2d46f7ad7041#diff-5bdf7e3437c9e47d597bda9e898d4c53L125-R135

Requirement  `'state' ptr must be aligned on 4-bytes boundaries` changed to `... and allocate it on 8-bytes boundaries`

**Comment by Cyan4973** [comment] 2020-10-31 09:10
> Here are the test results at MSVC 2008 (32-bit):
> (...)
> LZ4_stream_t_alignment() = 8

Indeed, `LZ4_stream_t_alignment()` should return `4` on 32-bit `x86` systems.

Is the issue limited to MSVC 2008 ?
I haven't been able to reproduce the issue on more modern versions of MSVC.

**Comment by remittor** [comment] 2020-10-31 09:53
> Is the issue limited to MSVC 2008 ?

Microsoft states that all compilers align `long long` by 8 bytes: https://docs.microsoft.com/en-us/cpp/cpp/alignment-cpp-declarations?view=msvc-160

**Comment by remittor** [comment] 2020-10-31 13:50
> I haven't been able to reproduce the issue on more modern versions of MSVC.

I created a test minimal program: https://pastebin.com/WmErc6N9
Results:
```
> test_align_vs2008.exe
sizeof(void*) = 4
LZ4_STREAMSIZE_U64 = 2052
LZ4_STREAMSIZE_U64 * 8 = 16416
sizeof(LZ4_stream_t_internal) = 16396
LZ4_stream_t_alignment() = 8

> test_align_vs2010.exe
sizeof(void*) = 4
LZ4_STREAMSIZE_U64 = 2052
LZ4_STREAMSIZE_U64 * 8 = 16416
sizeof(LZ4_stream_t_internal) = 16396
LZ4_stream_t_alignment() = 8

> test_align_vs2015.exe
sizeof(void*) = 4
LZ4_STREAMSIZE_U64 = 2052
LZ4_STREAMSIZE_U64 * 8 = 16416
sizeof(LZ4_stream_t_internal) = 16396
LZ4_stream_t_alignment() = 8

> test_align_vs2019.exe
sizeof(void*) = 4
LZ4_STREAMSIZE_U64 = 2052
LZ4_STREAMSIZE_U64 * 8 = 16416
sizeof(LZ4_stream_t_internal) = 16396
LZ4_stream_t_alignment() = 8
```

Compile options (VS2015): `/GS /GL /analyze- /W3 /Gy /Zc:wchar_t /Zi /Gm- /O2 /Fd"Release\vc140.pdb" /Zc:inline /fp:precise /D "WIN32" /D "NDEBUG" /D "_CONSOLE" /D "_UNICODE" /D "UNICODE" /errorReport:prompt /WX- /Zc:forScope /Gd /Oy- /Oi /MD /Fa"Release\" /EHsc /nologo /Fo"Release\" /Fp"Release\test_align.pch"`

**Comment by remittor** [comment] 2020-10-31 14:41
I checked alignment also on `gcc` v2.95 (2001, mingw 32-bit):
Function `LZ4_stream_t_alignment()` returned **8**.
`gcc.exe -S -std=c89 .....`

**Comment by Cyan4973** [comment] 2020-10-31 18:05
Thanks for the insightful feedback

It's very strange, it seems we are experiencing radically different outcomes.

Which version of `lz4` or `LZ4_stream_t_alignment()` are you testing ?

**Comment by remittor** [comment] 2020-10-31 20:19
> Which version of `lz4` or `LZ4_stream_t_alignment()` are you testing ?

HEAD of `dev` branch.

> It's very strange, it seems we are experiencing radically different outcomes.

Especially for you, I have conducted public open testing! Look this: https://godbolt.org/z/nGve9s
List of 32 bit compilers where type `long long` is 8 byte aligned:
```
ARM gcc 4.5.4 (linux)
ARMv7-a clang 9.x
ARMv8-a clang [-m32]
KALRAY MPPA gcc x.x.x [-m32]
RISC-V rv32gv clang
MIPS gcc 5.4
PowerPC gcc 4.8.5
PowerPC64 gcc 9.x [-m32]
PowerPC64 clang [-m32]
x86 msvc 2015
ARM msvc 2015
WebAssembly clang (trunc) [C++]
```

List of 32 bit compilers where type `long long` is 4 byte aligned:
```
X86_64 clang x.x.x [-m32]
X86_64 gcc x.x.x [-m32]
X86_64 ICC x.x.x [-m32]
X86 gcc 1.27
X86 djgpp 7.2.0  [C++]
ELLCC [-m32]
X86 ZAPCC [-m32]
```

List of 16 bit compilers where type `long long` is 2 byte aligned:
```
MSP430 gcc x.x.x
```

List of XX bit compilers where type `long long` is 1 byte aligned (not aligned):
```
AVR gcc x.x.x
SDCC 4.0.0
```

**Comment by Cyan4973** [comment] 2020-11-06 18:56
An important part of the investigation is to notice that on Linux x86 (32-bit), all versions of `gcc`, all versions of `clang` and all versions of `icc` do return an alignment of 4. This can be witnessed using the same [godbolt website](https://godbolt.org/z/sxT7jK).

Anyway, I hope this investigation puts to rest the assertion that structures containing a `long long` are necessarily aligned on 8 bytes. Nope, it depends on the [ABI](https://en.wikipedia.org/wiki/Application_binary_interface).

Which leads to the following question : who controls the ABI ?
At the very least, it's a combination of cpu type and operating system. Beyond that, it's less clear to me. I will presume that a compiler is not allowed to make its own choice when it comes to ABI, otherwise it would break interoperability, which is one of the main properties of `C`.

So Linux x86 (32-bit) defines an alignment of `4` for `long long`. But maybe Windows x86 defines an alignment of 8 ?

In theory, that's possible. 
But then, I don't understand why my own test results, using a Windows VM, nor Win32 results collected on Appveyor CI, which show that the `LZ4_stream_t` can be aligned on 4-bytes boundaries by the compiler, and that the alignment test work correctly for them.

Yet, the alignment test returns `8` for Visual compiler running on Wine on [godbolt](https://godbolt.org/z/5G1hqv). So why is there such a difference ? This is unclear.

At the end of the day, `4` or `8` is not even the actual issue.
Let's take a step back : the alignment test was primarily meant to ensure that, if someone uses the static definition of `LZ4_stream_t`, then it's _by definition_ correctly aligned, so the alignment test should return "true" (hence it can't be simplified as a generic `8`, it would break on 32-bit platforms).

But then, the problem became that, if someone allocates a memory region using `malloc()`, then it should also be considered "correctly aligned". That's because `malloc()` contract is presumed to ensure that it will provide a memory area correctly aligned for the largest alignment requirement of any (normal) C type (I believe it excludes specific types, such as `AVX512` ones).
Hence, if `long long` must be aligned on 8-bytes boundaries, then `malloc()` __must__ return a memory area aligned on 8-bytes.

https://en.cppreference.com/w/c/memory/malloc :
> If allocation succeeds, returns a pointer that is suitably aligned for any object type with fundamental alignment.

Therefore, a situation where `LZ4_stream_t` must be aligned on 8-bytes boundaries while `malloc()` returns a memory area merely aligned on 4-bytes boundaries is presumed _impossible_, as it would be a violation of `malloc()` contract. 

So why does it _nonetheless_ happen ? Let's consider a few hypothesis : 
- the test is incorrect, it returns 8 when it should return 4
- the `malloc()` implementation is fucked up, it should return a memory aligned on 8 bytes rather than 4
- the ABI is fucked up

The last 2 scenarios seem far fetched: I would expect such situations to trigger a myriad of problems, not limited to `lz4`.
But then, one of the difference I can (currently) witness, between my own tests on `win32` platforms, which return 4, and the ones that fail on `godbolt`, is that the `godbolt` tests are actually run on `wine`, not native `Windows`. Could it make a difference ? At this stage, it's unclear.

The first scenario, stating that the alignment test itself is incorrect, feels therefore more likely.
But then, the test is also so simple. It's unclear to me why it would be incorrect.

Without a clear explanation of what's going wrong, we are left with mitigation techniques, essentially disabling the alignment tests on "risky" platforms. It's unsatisfying, but on short term, we may not have a better option.

Of course, I would very much prefer to nail the answer to this conundrum before the incoming release, so I'm opened to suggestions and solutions related to this problem.

**Comment by remittor** [comment] 2020-11-06 20:47
> The first scenario, stating that the alignment test itself is incorrect, feels therefore more likely.

It was only in the lz4 project that I met such an attempt to predict the values ​​returned by malloc.
I don't think it's worth tying the `long long` alignment to the system memory manager. This was a very risky step.

**Comment by Cyan4973** [comment] 2020-11-06 22:49
Currently making `LZ4_ALIGN_TEST` controllable at build time

**Comment by Cyan4973** [comment] 2020-11-07 02:29
I think I've got a solution.
Currently tested in CI.

**Comment by Cyan4973** [comment] 2020-11-07 03:57
OK, I believe this last solution works.

It doesn't answer the specific question of `long long` alignment on `win32` setup,
but it circumvents the problem by no longer depending on it.

**Closed as completed** 2020-11-07 04:27 UTC

**Comment by remittor** [comment] 2020-11-07 15:53
> Hence, if `long long` must be aligned on 8-bytes boundaries, then `malloc()` **must** return a memory area aligned on 8-bytes.
> > If allocation succeeds, returns a pointer that is suitably aligned for any object type with **fundamental alignment.**

The reference to `fundamental alignment` appeared only in the `С11` and `C++11` standard.
C11 [7.22.3]: http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf 
C++11 [5.3.4.11]: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3690.pdf

In previous standards, there was no such term at all.
C99 [7.20.3]: http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf 
C++03 [3.7.3.1]: https://github.com/hstefan/htlib/raw/master/res/INCITS%2BISO%2BIEC%2B14882-2003.pdf
