### ISSUE TITLE
`make test` fails on armhf with musl libc

### ISSUE THREAD

**Issue by ncopa** [lz4/lz4#451] opened 2018-01-16 16:25 UTC
Running `make test` on alpine linux (with musl libc) fails on armhf. x86, x86_64, ppc64le and s390x seems to work.

This is where it ends:
````
stdin                : decoded 3221225472 bytes                                
 1-LZ4_decompress_fast           :     18092 ->    81.6 MB/s
 3-LZ4_decompress_fast_usingDict :     18092 ->    82.2 MB/s
 4-LZ4_decompress_safe           :     18092 ->    93.0 MB/s
 6-LZ4_decompress_safe_usingDict :     18092 ->    95.7 MB/s
 7-LZ4_decompress_safe_partial   :     18092 ->    95.4 MB/s
 8-LZ4_decompress_safe_forceExtD :     18092 ->    95.3 MB/s
 9-LZ4F_decompress               :     18092 ->    91.0 MB/s
 27782 -rw-r--r--    1 root     root     3221225472 Jan 16 16:02 tmplc2
diff -s tmplc1 tmplc2
Files tmplc1 and tmplc2 are identical

Compressed 6442450944 bytes into 3814385500 bytes ==> 59.21%                   
./datagen -g6GB   | ../programs/lz4 -v5BD  | ../programs/lz4 -qt
*** LZ4 command line interface 32-bits v1.8.0, by Yann Collet ***

Compressed 6442450944 bytes into 2896075073 bytes ==> 44.95%                   
make[1]: Leaving directory '/home/ncopa/aports/main/lz4/src/lz4-1.8.1/tests'
make: *** [Makefile:127: test] Error 2
````

Any ideas how to troubleshoot this?

Here is a full build log (on different armhf container)
https://gist.github.com/ncopa/8637c7735a3076c0dd895fe2124d3bf1

**Comment by Cyan4973** [comment] 2018-01-16 17:58
Hard to tell.
At least we know the command which is supposed to create this error : 
` ./datagen -g6GB   | ../programs/lz4 -v5BD  | ../programs/lz4 -qt `
now there's something to test.

I would be immediately worried about the `-g6GB` : this is a 6 GB test, and sometimes, 32-bit systems have trouble with large inputs.

To better investigate, one would need direct access to a failing system, in order to analyse more thoroughly and add some traces. Note [ARM architecture is already tested](https://travis-ci.org/lz4/lz4/jobs/328878359) using `qemu`, but without error, so the issue is not "just arm", and needs a number of conditions to reproduce.

**Comment by Cyan4973** [comment] 2018-04-09 22:51
Any idea how to reproduce this issue ?

**Comment by felixhandte** [comment] 2018-04-14 00:48
Hi, @ncopa, can you share more details about how to reproduce this failure?

I was unable to repro using musl on 32 bit Raspbian (armv7l, linux 4.9.35-v7+, gcc 4.9.2, musl commit ae2a01d).

**Comment by Cyan4973** [comment] 2018-09-05 23:28
Is there still a problem regarding `lz4` tests on alpine linux for armhf ?

Quick googling delivers this : 
https://pkgs.alpinelinux.org/package/v3.8/main/armhf/lz4

which I interpret as : "it works fine on alpine linux for armhf".

Save any news on this topic, I'll close this thread in the near future.

**Closed** 2018-09-10 20:12 UTC
Labels: test failure
