### ISSUE TITLE
Provide lz4frame.h functionality to handle old frame format specs

### ISSUE THREAD

**Issue by nh2** [lz4/lz4#607] opened 2018-11-24 22:13 UTC
Hi,

I'm writing a binding to `lz4frame.h` from another programming language (Haskell in my case).

One thing I find challenging, where I find that the lz4 library doesn't help as much as it could yet, is handling changes in the frame format.

In my binding I would ideally not have to deal with the frame format spec at all and let everything be handled by the lz4 library. But there are certain cases where the library doesn't provide the info needed, and I have to drop down to relying on statements of the frame format directly. Obviously that means my binding will stop working when the format spec is updated.

---

Concrete example follows:

Using my library I can request input bytes from some pipe (e.g. actual pipe, or socket). As you know, you have to provide `read()` with the amount of data to expect; if you ask for too much, it's going to block until more data has arrived, so it's important to know what the minimum number of bytes to request is to do the next step.

I want to be able to retrieve info about an incoming lz4 stream as soon as possible, in particular I want to call `LZ4F_getFrameInfo()` to extract meta information.

The problem is that `LZ4F_getFrameInfo()` requires:

```
 *     Input size must be large enough to successfully decode the entire frame header.
 *     Frame header size is variable, but is guaranteed to be <= LZ4F_HEADER_SIZE_MAX bytes.
```

Now that makes things difficult, because it doesn't tell me what the _minimum_ amount of bytes is that I have to `read()` from my stream, only the maximum.

If I read `LZ4F_HEADER_SIZE_MAX` from the stream, I may block unnecessarily, because I'm (at the time of writing) waiting for 19 bytes, while it's possible that the header is only 7 bytes long. So if the other side creates a header, sends it, and then takes a while to create the first block, and then sends it, then I will block for the entire duration even though I could already successfully read the header (and tell the user promptly, for example, some information about the incoming stream).

So what I did so far was to `read()` the first 5 bytes (because I know every valid header must have them), then look at the 5th byte (the FLG byte), and check if the 3rd (content size bit). Based on it, I can compute the actual size of the header (2 more bytes to read if it's not set, 2+8 more bytes if it's set), and `read()` that amount from the pipe in order to pass it `LZ4F_getFrameInfo()`.

But as you can tell from the numbers, this was only the case until https://github.com/lz4/lz4/commit/e98a528576c1cc095dcdcf9ff1f4e3e8422a535d landed.

This commit extended the length of the header by another dynamic field, so the code I wrote became wrong now, and broke with `ERROR_frameHeader_incomplete`.

This situation could be solved if `lz4frame.h` provided some macros or functions that allowed me to extract this information, so that I can rely only on the API, and don't have to inspect bits from the spec.

For example, perhaps a function like

```c
size_t LZ4F_getHeaderSize(const void* srcBuffer, size_t* srcSizePtr, size_t* outSize)
```

could be added, which

* if there are enough bytes in `srcBuffer` to determine it, tells me how long the header must be (writes it into `*outSize`)
* if there aren't enough bytes in `srcBuffer` to determine it, returns how many more bytes of input are needed to determine it, so I can `read()` that many more bytes from the pipe

Does that make sense?

**Comment by Cyan4973** [comment] 2018-11-27 00:42
I agree, the process to retrieve the frame header size is not straightforward enough.

Right now, it's possible to use `LZ4F_getFrameInfo()`.
Start at 7 bytes, which is the minimum frame header length
(alternatively, you could start from 7+4=11 bytes, which is the guaranteed minimum frame length, generating an empty frame).

Provide that input to `LZ4F_getFrameInfo()`.
If it fails with error `frameHeader_incomplete`, add one byte, retry.
The functions guarantees that it does not modify the state when it fails.
After a limited number of attempts (since `LZ4F_HEADER_SIZE_MAX = 19`), it will necessarily succeed, or produce a different error.

I agree that it's not great, it's more a work-around, available now.

The function `LZ4F_headerSize()` already exists, it's just not exposed on the public side.
Maybe all that is needed is to expose it (and maybe strengthen it against extended error conditions).

**Comment by Cyan4973** [comment] 2019-04-09 23:47
Actually, it might not be necessary to add a new function for this.

The main problem is : how much bytes are necessary for `LZ4_getFrameInfo()` to successfully return with a filled `LZ4F_frameInfo_t` structure.

Well, we already know this minimum, it's 5 bytes.
So make it a constant, and give it a proper name.

On providing `LZ4_getFrameInfo()` with an input of 5 bytes, the function will fail, but will return the exact number of bytes it needs to decode the header, aka, the header size.

Let's emphasize that this is the intended behavior when trying to feed `LZ4_getFrameInfo()` with the absolute minimum nb of bytes (since it works fine with more bytes too).

**Comment by Cyan4973** [comment] 2019-04-10 04:30
associated patch merged

**Closed by Cyan4973** 2019-04-10 04:30 UTC
Labels: enhancement
