### ISSUE TITLE
 Missing symbol LZ4_versionString

### ISSUE THREAD

**Issue by ignatenkobrain** [lz4/lz4#301] opened 2017-01-05 09:12 UTC
from https://bugzilla.redhat.com/show_bug.cgi?id=1410352

Description of problem:
Missing symbol LZ4_versionString

Version-Release number of selected component (if applicable):
lz4-1.7.4.2-1.fc25

How reproducible:
Always

Steps to Reproduce:
1. grep LZ4_version /usr/include/lz4*
2. objdump -T /usr/lib64/liblz4.so.1.7.4 | grep Version
3.

Actual results:
$ grep LZ4_version /usr/include/lz4*
LZ4LIB_API int LZ4_versionNumber (void);
LZ4LIB_API const char* LZ4_versionString (void);
$ objdump -T /usr/lib64/liblz4.so.1.7.4  | grep LZ4_version
0000000000002be0 g    DF .text	0000000000000006  Base        LZ4_versionNumber

Expected results:
Both LZ4_versionNumber and Z4_versionString available

Additional info:
Trying to use this function, with system liblz4, raise a critical error: undefined symbol: LZ4_versionString

**Comment by remicollet** [comment] 2017-01-05 10:20
I think this is a duplicate of #283 fixed in https://github.com/lz4/lz4/commit/5eb547a6080b8e63b5e522b448e31052fbc6b927

**Closed** 2017-01-05 10:30 UTC
